### ISSUE TITLE
[Grafana] Gestion permissions et dashboard

### ISSUE THREAD

**Issue by BriceMichalski** [Ynov-Monitoring/deployment#10]
Besoin: pour chaque project faisant appel à nos service nous devons mettre en place : 

- [ ]  un user
- [ ] un groupe 
- [ ] un dossier dédié et un dashboard basic

**Comment by Bapt0u** [comment]
linked to issue #8

**Comment by Bapt0u** [comment]
Etat de l'avancement du ticket : 
- [x] Création de users à partir d'une liste sous format YAML 
- [x] Création d'une équipe (TEAM) en se basant sur le nom du projet renseigner dans la liste
- [x]  Ajout de l'utilisateur dans son équipe 
- [x]  Création d'un dossier pouvant accueillir les dashboard d'équipe 
- [x] Ajout des droits en lecteur seul pour l'équipe sur son dossier 

Manque : 
- [ ] Ajout d'un dashboard basique par défaut

**Comment by BriceMichalski** [comment]
ça a été poussé les modifs de lundi ?

**Comment by Bapt0u** [comment]
Yes tout y est et ça fonctionne de mon côté

**Comment by BriceMichalski** [comment]
Okay niquel ! ça sera finis ce week end ça c'est sur !
