### ISSUE TITLE
[Influxdb] Définir et Aplliquer les retention policy

### ISSUE THREAD

**Issue by BriceMichalski** [Ynov-Monitoring/deployment#27]
- [ ] Définir une stratégie de sauvegarde
- [ ] Appliquer cette stratégie

**Comment by IxArgon** [comment]
**CONTENU DU FICHIER (prévu pour la documentation)**

**
1.  \\RETENTION//
**

- 1mois

CREATE RETENTION POLICY "R1" ON "monitoring" DURATION 1h REPLICATION 1 DEFAULT
- 6mois
- 
CREATE RETENTION POLICY "R2" ON "monitoring" DURATION 6h REPLICATION 1

**
2. \\CONTINUOUS QUERY//
**
CREATE CONTINUOUS QUERY "CR1" ON "monitoring" RESAMPLE EVERY 1m BEGIN SELECT mean(*) INTO "R2"."cpu" FROM "cpu" GROUP BY time(1m),* END
